import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/*metadataオブジェクトにはアプリケーションのメタデータが含まれています。これらのメタデータは、
アプリケーションのタイトルと説明を定義するのに使用されます*/
export default function RootLayout({ children }) {
  return (
/*children プロパティを引数として受け取ります。これは、RootLayout コンポーネントの中に配置された他のコンポーネントや要素を表します。*/
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
        <Navbar /> //Navbar コンポーネントがこのコンテナ内に配置されており、ナビゲーションバーを表示するためのものです。
        <div className="mt-8">{children}</div>
        </div>
        </body>
    </html>
  );
}
//children プロパティには、RootLayout コンポーネントに渡された子要素が配置されています。これにより、アプリケーションのメインコンテンツが表示されます。